# This file is a template, and might need editing before it works on your project.
# Select image from https://hub.docker.com/_/php/
image: node:latest

stages:
  - build
  - docker
  - deploy
  # Select what we should cache between builds

build:resources:
  before_script:
    - apt-get update
  script:
    - npm install --include=dev --cache ../.npm-cache
    - npm run build
  artifacts:
    untracked: true
  stage: build
  cache:
    paths:
      - .npm-cache

docker:
  image: docker:git
  stage: docker
  dependencies:
    - build:resources
  needs:
    - build:resources
  only:
    - master
  cache:
    paths:
      - .npm-cache
  script:
    - sed 's/# DEPLOY //g' Dockerfile > Dockerfile.deploy
    - docker build --pull -t "$CI_REGISTRY_IMAGE" . -f Dockerfile.deploy
    - docker tag "$CI_REGISTRY_IMAGE" "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
    - docker push "$CI_REGISTRY_IMAGE"
    - docker push "$CI_REGISTRY_IMAGE:$CI_COMMIT_SHA"
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD" $CI_REGISTRY

deploy:
  image: curlimages/curl
  stage: deploy
  script:
    - curl -X POST http://10.13.37.4:9000/api/webhooks/4d0fb6cf-dceb-4987-9eb8-a12d4a1102c1
